# coding=UTF-8

shows = {
  u'-': None,
  u'------': None,
  u'...': None,
  u'.hack//sign': u'.hack//Sign',
  u'12 kingdoms': u'12 kingdoms - Google Search',
  u'5 centimeter per second': u'5 Centimeters Per Second',
  u'5 centimeters per second': u'5 Centimeters Per Second',
  u'5 centimeters per second  5 centimeters per second': u'5 Centimeters Per Second',
  u'5 cm per second': u'5 Centimeters Per Second',
  u'[c]': u'[C]: The Money of Soul and Possibility Control',
  u'a certain magical index': u'Toaru Majutsu no Index',
  u'ah my goddess': u'Oh! My Goddess!',
  u'air gear': u'Air Gear',
  u'aka to test to shoukanjuu': u'Baka to Test to Shoukanjuu',
  u'akagi': u'Akagi',
  u'amagami ss': u'Amagami SS',
  u'angel beats': u'Angel Beats!',
  u'angel beats!': u'Angel Beats!',
  u'anidb': None,
  u'ano hana': u'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai',
  u'ano hi mita hana no namae wo bokutachi wa mada shiranai': u'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai',
  u'anohana': u'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai',
  u'another': u'Another',
  u'anything by ghibli': None,
  u'anything harem': None,
  u'appleseed ex machina': u'Appleseed',
  u'aria': u'Aria Series',
  u'aria the origination': u'Aria Series',
  u'aria:the animation': u'Aria Series',
  u'astarotte no omocha': u'Astarotte no Omocha!',
  u'avatar:legend of korra': None,
  u'azumagna daioh': u'Azumanga Daioh',
  u'azumanga daioh': u'Azumanga Daioh',
  u'baccano': u'Baccano!',
  u'baccano!': u'Baccano!',
  u'baccano!!': u'Baccano!',
  u'bakemonogatari': u'Bakemonogatari',
  u'bakuman': u'Bakuman',
  u'bamboo blade': u'Bamboo Blade',
  u'bebop': u'Cowboy Bebop',
  u'beck': u'Beck: Mongolian Chop Squad',
  u'beck: mongolian chop squad': u'Beck: Mongolian Chop Squad',
  u'ben-to': u'Ben-To',
  u'berserk': u'Berzerk',
  u'bible black and boku no pico': None,
  u'black butler': u'Black Butler',
  u'black lagoon': u'Black Lagoon',
  u'black rock shooter': u'Black☆Rock Shooter',
  u'bleach': u'Bleach',
  u'blood+': u'Blood+',
  u'boku no pico': None,
  u'bokusatsu tenshi dokuro-chan': u'Bokusatsu Tenshi Dokuro-chan',
  u'break blade': u'Broken Blade',
  u'can\'t choose': None,
  u'cannot answer this x(': None,
  u'cant answer ': None,
  u'cant choose': None,
  u'cant decide between beck or eden of the east': u'',
  u'cant even compare': u'',
  u'cant pick a specific one.': u'',
  u'card captor sakura': u'Cardcaptor Sakura',
  u'cardcaptor sakura': u'Cardcaptor Sakura',
  u'cardcaptors sakura': u'Cardcaptor Sakura',
  u'carnival phantasm': u'Carnival Phantasm',
  u'carnival phantasm ': u'Carnival Phantasm',
  u'cat soup': u'Cat Soup',
  u'chobits': u'Chobits',
  u'clannad': u'Clannad',
  u'clannad ': u'Clannad',
  u'clannad (1st & 2nd seasons)': u'Clannad',
  u'clannad (atm)': u'Clannad',
  u'clannad (pref. after story)': u'Clannad: After Story',
  u'clannad : after story': u'Clannad: After Story',
  u'clannad after story': u'Clannad: After Story',
  u'clannad after story ': u'Clannad: After Story',
  u'clannad afterstory': u'Clannad: After Story',
  u'clannad as': u'Clannad: After Story',
  u'clannad ~after story~': u'Clannad: After Story',
  u'clannad/after story': u'Clannad: After Story',
  u'clannad/as': u'Clannad: After Story',
  u'clannad: after story': u'Clannad: After Story',
  u'clannad:afterstory': u'Clannad: After Story',
  u'code geass': u'Code Geass',
  u'code geass ': u'Code Geass',
  u'code geass or fairy tail': u'Fairy Tail',
  u'code geass r2': u'Code Geass',
  u'code geauss': u'Code Geass',
  u'code;geass': u'Code Geass',
  u'cowboy beboops': u'Cowboy Bebop',
  u'cowboy bebop': u'Cowboy Bebop',
  u'cowboy bebop and nge': u'Neon Genesis Evangelion',
  u'cowboy bebop/stein\'s gate': u'Steins;Gate',
  u'cowboy bepop': u'Cowboy Bebop',
  u'crest of the stars': u'Crest of the Stars',
  u'cross game': u'Cross Game',
  u'daicon iv': u'Daicon IV',
  u'dantalian no shoka': u'Dantalian no Shoka',
  u'darker than black': u'Darker than Black',
  u'darker than black, nigga!': u'Darker than Black',
  u'dbz': u'Dragon Ball Z',
  u'death note': u'Death Note',
  u'death note ': u'Death Note',
  u'death note / tengen toppa gurren lagan': u'Tengen Toppa Gurren Lagann',
  u'death note, code geass, spice and wolf': u'Spice and Wolf',
  u'deathnote': u'Death Note',
  u'dennou coil': u'Dennō Coil',
  u'denpa teki na kanojo': u'Denpa teki na Kanojo',
  u'desert punk': u'Desert Punk',
  u'detective conan': u'Detective Conan',
  u'diebuster': u'Diebuster',
  u'digimon': u'Digimon',
  u'disappearance of haruhi': u'Haruhi Suzumiya series',
  u'dn angel': u'D.N.Angel',
  u'don\'t have a favorite, like most of what i see': None,
  u'don\'t have one': None,
  u'don\'t have one yet': None,
  u'don\'t remember': None,
  u'dont have one': None,
  u'dragon ball': u'Dragon Ball Series',
  u'dragon ball z': u'Dragon Ball Series',
  u'dragonball': u'Dragon Ball Series',
  u'dragonball series': u'Dragon Ball Series',
  u'dragonball z': u'Dragon Ball Series',
  u'drangonball za ': u'Dragon Ball Series',
  u'dunno': None,
  u'durarara': u'Durarara!!',
  u'durarara!!': u'Durarara!!',
  u'dxd': u'High School DxD',
  u'ef': u'ef tale of series',
  u'ef a tale of memories': u'ef: tale of series',
  u'ef- a tale of memories': u'ef: tale of series',
  u'el cazador de la bruja': u'El Cazador de la Bruja',
  u'elemental gelade': u'Elemental Gelade',
  u'elfen lied': u'Elfen Lied',
  u'end of evangelion': u'Evangelion series',
  u'ergo proxy': u'Ergo Proxy',
  u'escaflowne': u'The Vision of Escaflowne',
  u'eureka 7': u'Eureka Seven',
  u'eureka seven': u'Eureka Seven',
  u'eureka seven ': u'Eureka Seven',
  u'eva': u'Evangelion series',
  u'evangelion': u'Evangelion series',
  u'eve no jikan': u'Time of Eve ',
  u'excel saga': u'Excel Saga',
  u'fae/zero': u'Fate/Zero',
  u'fairy tail': u'Fairy Tail',
  u'fairytail': u'Fairy Tail',
  u'fate zero': u'Fate/Zero',
  u'fate/ zero': u'Fate/Zero',
  u'fate/stay night': u'Fate/stay night',
  u'fate/zero': u'Fate/Zero',
  u'fate/zero ': u'Fate/Zero',
  u'favorite?': None,
  u'flcl': u'FLCL',
  u'fma': u'Fullmetal Alchemist',
  u'fma b': u'Fullmetal Alchemist: Brotherhood',
  u'fma brotherhood': u'Fullmetal Alchemist: Brotherhood',
  u'fma original': u'Fullmetal Alchemist',
  u'fma: b': u'Fullmetal Alchemist: Brotherhood',
  u'fma: brotherhood': u'Fullmetal Alchemist: Brotherhood',
  u'fma:b': u'Fullmetal Alchemist: Brotherhood',
  u'fma:brotherhood': u'Fullmetal Alchemist: Brotherhood',
  u'fma;b ': u'Fullmetal Alchemist: Brotherhood',
  u'fooly cooly': u'FLCL',
  u'freezing': u'Freezing',
  u'fruits basket': u'Fruits Basket',
  u'fuck this question.': None,
  u'full metal alchemist': u'Fullmetal Alchemist',
  u'full metal alchemist ': u'Fullmetal Alchemist',
  u'full metal alchemist & fma:brotherhood': u'',
  u'full metal alchemist (2004)': u'Fullmetal Alchemist',
  u'full metal alchemist brotherhood': u'Fullmetal Alchemist: Brotherhood',
  u'full metal alchemist: brotherhood': u'Fullmetal Alchemist: Brotherhood',
  u'full metal alchemist:brotherhood': u'Fullmetal Alchemist: Brotherhood',
  u'full metal panic': u'Full Metal Panic! ',
  u'full metal panic!': u'Full Metal Panic! ',
  u'full metal panic? fumoffu': u'Full Metal Panic? Fumoffu',
  u'fullmeta alchemist: brotherhood': u'Fullmetal Alchemist: Brotherhood',
  u'fullmetal alchemist': u'Fullmetal Alchemist',
  u'fullmetal alchemist + brotherhood': u'Fullmetal Alchemist: Brotherhood',
  u'fullmetal alchemist brotherhood': u'Fullmetal Alchemist: Brotherhood',
  u'fullmetal alchemist: brotherhood': u'Fullmetal Alchemist: Brotherhood',
  u'fullmetal alchemist:brotherhood': u'Fullmetal Alchemist: Brotherhood',
  u'furi kuri': u'FLCL',
  u'ga rei zero': u'Ga-Rei: Zero',
  u'galaxy express 999': u'Galaxy Express 999',
  u'gankutsuou': u'Gankutsuou',
  u'gantz': u'Gantz',
  u'geass r2': u'Code Geass',
  u'genshiken': u'Genshiken',
  u'ghost in the shell': u'Ghost in the Shell Series',
  u'ghost in the shell s.a.c': u'Ghost in the Shell Series',
  u'ghost in the shell sac': u'Ghost in the Shell Series',
  u'ghost in the shell series (movies+tv)': u'Ghost in the Shell Series',
  u'ghost in the shell stand alone complex': u'Ghost in the Shell Series',
  u'ghost in the shell standalone complex': u'Ghost in the Shell Series',
  u'ghost in the shell: innocence': u'Ghost in the Shell Series',
  u'ghost in the shell: sac': u'Ghost in the Shell Series',
  u'ghost in the shell: sal': u'Ghost in the Shell Series',
  u'ghost in the shell: stand alone complex': u'Ghost in the Shell Series',
  u'gintama': u'Gintama',
  u'gits': u'Ghost in the Shell Series',
  u'gits: sac 2nd gig': u'Ghost in the Shell Series',
  u'glass mask': u'Glass Mask',
  u'golden boy': u'Golden Boy',
  u'good question': None,
  u'gosick': u'Gosick',
  u'gosick or angel beats': u'Gosick',
  u'gosick!': u'Gosick',
  u'great teacher onizuka': u'Great Teacher Onizuka',
  u'gto': u'Great Teacher Onizuka',
  u'guilty crown': u'Guilty Crown',
  u'gunbuster': u'Gunbuster',
  u'gundam': u'Gundam Series',
  u'gundam 00': u'Gundam Series',
  u'gundam series': u'Gundam Series',
  u'gundam unicorn': u'Gundam Unicorn',
  u'gundam wing': u'Gundam Series',
  u'gungrave': u'Gungrave',
  u'gunslinger girl': u'Gunslinger Girl',
  u'gunslinger girl (1st season)': u'Gunslinger Girl',
  u'gunslinger girls': u'Gunslinger Girl',
  u'gurren lagan': u'Tengen Toppa Gurren Lagann',
  u'gurren lagann': u'Tengen Toppa Gurren Lagann',
  u'gurren lagann tengen toppa': u'Tengen Toppa Gurren Lagann',
  u'gurren laggan': u'Tengen Toppa Gurren Lagann',
  u'gurren laggann': u'Tengen Toppa Gurren Lagann',
  u'gurtrn laggan': u'Tengen Toppa Gurren Lagann',
  u'h20 footprints in the sand': u'H2O: Footprints in the Sand',
  u'h2o foot prints in the sand': u'H2O: Footprints in the Sand',
  u'haibane renmei': u'Haibane Renmei',
  u'haiyore! nyaruko-san': u'Haiyore! Nyarlko-san',
  u'hajime no ippo': u'Hajime no Ippo',
  u'hajime no ippo ': u'Hajime no Ippo',
  u'hana no yori dango': u'Hana Yori Dango',
  u'hanbun': u'Hanbun no Tsuki ga Noboru Sora',
  u'hard to choose... probably ouran highschool host club.': u'Ouran High School Host Club',
  u'hard to choose… ': None,
  u'hard to decide, and this changes way too often. its currently kara no kyoukai': u'Kara no Kyoukai',
  u'hard to say, perhaps baccano or haruhi': None,
  u'haruhi': u'Haruhi Suzumiya Series',
  u'haruhi suzumiya': u'Haruhi Suzumiya Series',
  u'hayate no gotoku': u'Hayate no Gotoku!',
  u'hellsing': u'Hellsing',
  u'hellsing ova': u'Hellsing Ultimate',
  u'hellsing ultimate ova': u'Hellsing Ultimate',
  u'hetalia': u'Hetalia: Axis Powers',
  u'hidamari sketch': u'Hidamari Sketch',
  u'high school of the dead': u'Highschool of the Dead',
  u'high school of the dead ': u'Highschool of the Dead',
  u'highschool dxd': u'High School DxD',
  u'highschool of the dead': u'Highschool of the Dead',
  u'higurashi': u'Higurashi Series',
  u'higurashi (when they cry)': u'Higurashi Series',
  u'higurashi no koro ni kai': u'Higurashi Series',
  u'higurashi no naku koro ni': u'Higurashi Series',
  u'higurashi no naku koro ni ': u'Higurashi Series',
  u'higurashi no naku koro ni kai': u'Higurashi Series',
  u'hikaru no go': u'Hikaru no Go',
  u'honey & clover': u'Honey and Clover',
  u'honey and clover': u'Honey and Clover',
  u'howl\'s moving castle': u'Howl\'s Moving Castle',
  u'hunter x hunter': u'Hunter × Hunter',
  u'hunter x hunter (original)': u'Hunter × Hunter (Original)',
  u'hunterxhunter': u'Hunter × Hunter',
  u'i can\'t narrow it down to just one, sorry.': None,
  u'i don\'t have one favorite ': None,
  u'i don\'t know': None,
  u'i dont have one favorit': None,
  u'i have yet to see it.': None,
  u'i\'m not sure, there are many. ': None,
  u'ichigo mashimaro': u'Ichigo Mashimaro',
  u'impossible': None,
  u'initial d': u'Initial D',
  u'inuyasha': u'Inuyasha',
  u'juuni kokki / twelve kingdoms': u'Juuni Kokuki',
  u'k-on': u'K-On!',
  u'k-on!': u'K-On!',
  u'k-on!!': u'K-On!',
  u'kaiji': u'Kaiji',
  u'kami nomi zo shiru sekai': u'The World God Only Knows',
  u'kara no kyoukai': u'Kara no Kyoukai',
  u'katanagatari': u'Katanagatari',
  u'kaze no stigma': u'Kaze no Stigma',
  u'kenichi': u'Kenichi: The Mightiest Disciple',
  u'kenshin': u'Rurouni Kenshin',
  u'kiba': u'Kiba',
  u'kimi ga nozomu eien': u'Kimi ga Nozomu Eien',
  u'kimi ni todoke': u'Kimi ni Todoke',
  u'kino no tabi': u'',
  u'kino\'s journey': u'Kino no Tabi: The Beautiful World',
  u'kodomo no omocha': u'Kodomo no Omocha',
  u'kokoro connect': u'Kokoro Connect',
  u'kore wa zombie desu ka': u'Kore wa Zombie Desu ka?',
  u'kore wa zombie desu ka?': u'Kore wa Zombie Desu ka?',
  u'kyoukaisen-jou no horizon': u'Kyoukaisenjou no Horizon',
  u'lain': u'Serial Experiments Lain',
  u'last exile': u'Last Exile',
  u'legend of galactic heroes': u'Legend of the Galactic Heroes',
  u'legend of the galactic heroes': u'Legend of the Galactic Heroes',
  u'legends of the galactic heroes': u'Legend of the Galactic Heroes',
  u'love hina': u'Love Hina',
  u'lovely complex': u'Lovely Complex',
  u'lucky star': u'Lucky Star',
  u'lupin': u'Lupin III',
  u'macross': u'Macross Series',
  u'macross 7': u'Macross Series',
  u'macross frontier': u'Macross Series',
  u'macross frontiers': u'Macross Series',
  u'madlax': u'Madlax',
  u'madoka': u'Puella Magi Madoka Magica',
  u'madoka magica': u'Puella Magi Madoka Magica',
  u'madoka magika': u'Puella Magi Madoka Magica',
  u'magic knight rayearth': u'Magic Knight Rayearth',
  u'mahoromatic': u'Mahoromatic',
  u'mahou shoujo lyrical nanoha a\'s': u'Mahou Shoujo Lyrical Nanoha A\'s',
  u'mahou shoujo madoka magica': u'Puella Magi Madoka Magica',
  u'mahou shoujo madoka★magica': u'Puella Magi Madoka Magica',
  u'mai-hime': u'Mai-Hime',
  u'major': u'Major Series',
  u'mars of destruction': u'Mars of Destruction',
  u'master of martial hearts': u'Master of Martial Hearts',
  u'mawaru penguindrum': u'Mawaru Pingudoramu',
  u'mayo chiki': u'Mayo Chiki!',
  u'mazinger z': u'Mazinger Z',
  u'melancholy of haruhi suzumiya': u'Haruhi Suzumiya Series',
  u'metropolis': u'Metropolis',
  u'minami-ke': u'Minami-ke',
  u'mirai nikki': u'Mirai Nikki',
  u'mitsudomoe': u'Mitsudomoe',
  u'mobile fighter g gundam': u'',
  u'mobile suit gundam unicorn': u'Mobile Fighter G Gundam',
  u'monogatari series': u'Bakemonogatari',
  u'mononoke': u'Mononoke',
  u'mononoke, or princess jellyfish': u'Princess Jellyfish',
  u'monster': u'Monster',
  u'mushi-shi': u'Mushishi',
  u'mushishi': u'Mushishi',
  u'mushishu': u'Mushishi',
  u'my bride is a mermaid': u'Seto no Hanayome',
  u'my neighbor totoro': u'My Neighbor Totoro',
  u'n/a': None,
  u'nana': u'Nana',
  u'naruto': u'Naruto',
  u'naruto: shippuden': u'Naruto: Shippuden',
  u'natsume yuujinchou': u'Natsume Yuujinchou',
  u'nausicaa of the valley of wind': u'Nausicaä of the Valley of the Wind',
  u'nazo no kanojo x': u'Nazo no Kanojo X',
  u'neon genesis evangelion': u'Evangelion Series',
  u'neon genesis evangelion ': u'Evangelion Series',
  u'neon gensis evangelion': u'Evangelion Series',
  u'nge': u'Evangelion Series',
  u'nhk ni youkoso': u'Welcome to the N.H.K.',
  u'nichijou': u'Nichijou',
  u'nisemonogatari': u'Bakemonogatari',
  u'nodame cantabile': u'Nodame Cantabile',
  u'none': None,
  u'now and then, here and there': u'Now and Then, Here and There',
  u'nurarihyon no mago': u'Nurarihyon no Mago',
  u'one outs': u'One Outs',
  u'one piece': u'One Piece',
  u'one piece ': u'One Piece',
  u'onegai twins': u'Onegai Twins',
  u'ore no imouto ga konnani kawaii wake ga nai': u'Ore no Imouto ga Konnani Kawaii Wake ga Nai',
  u'oreimo': u'Ore no Imouto ga Konnani Kawaii Wake ga Nai',
  u'otome wa boku ni koishiteru': u'Otome wa Boku ni Koishiteru',
  u'our high school host club': u'Ouran High School Host Club',
  u'ouran high host club': u'Ouran High School Host Club',
  u'ouran high school host club': u'Ouran High School Host Club',
  u'outlaw star': u'Outlaw Star',
  u'pandora hearts': u'Pandora Hearts',
  u'paprika': u'Paprika',
  u'paradise kiss': u'Paradise Kiss',
  u'perfect blue': u'Perfect Blue',
  u'phantom: requiem for the phantom': u'Phantom: Requiem for the Phantom',
  u'planates': u'Planetes',
  u'planetes': u'Planetes',
  u'pmmm': u'Puella Magi Madoka Magica',
  u'porco rosso': u'Porco Rosso',
  u'princess mononoke': u'Princess Mononoke',
  u'princess tutu': u'Princess Tutu ',
  u'puella magi madoka magica': u'Puella Magi Madoka Magica',
  u'r.o.d.': u'R.O.D.',
  u'rahxephon': u'Rahxephon',
  u'ranma': u'Ranma ½',
  u'ranma 1/2': u'Ranma ½',
  u'revolutionary girl utena': u'Revolutionary Girl Utena',
  u'romance is in the flash of the sword ii ': u'Romance is in the Flash of the Sword II',
  u'rurouni kenshin': u'Rurouni Kenshin',
  u'rurouni kenshin tsuiokuhen': u'Rurouni Kenshin',
  u'rurouni kenshin: tsuiokuhen': u'Rurouni Kenshin',
  u'sailor moon': u'Sailor Moon',
  u'saint seiya': u'Saint Seiya',
  u'samurai champloo': u'Samurai Champloo',
  u'samurai x': u'Rurouni Kenshin',
  u'samurai x: trust and betrayal': u'Rurouni Kenshin',
  u'sankarea': u'Sankarea',
  u'sayonara zetsubou sensei': u'Sayonara, Zetsubou-Sensei',
  u'sayonara zetsubou sensei and clannad after story': u'Sayonara, Zetsubou-Sensei',
  u'school days': u'School Days',
  u'school rumble': u'School Rumble',
  u'seirei no moribito': u'Seirei no Moribito',
  u'seitokai no ichizon': u'Seitokai no Ichizon',
  u'sekirei': u'Sekirei',
  u'serial experiments lain': u'Serial Experiments Lain',
  u'serial experiments: lain': u'Serial Experiments Lain',
  u'seriously?': None,
  u'shakugan no shana': u'Shakugan no Shana',
  u'shamen king': u'Shaman King',
  u'she and her cat': u'She and Her Cat',
  u'shigofumi': u'Shigofumi',
  u'shoujo kakume utena': u'Revolutionary Girl Utena',
  u'shuffle!': u'Shuffle!',
  u'simoun': u'Simoun',
  u'slam dunk': u'Slam Dunk',
  u'slayers': u'Slayers',
  u'sora no manimani': u'Sora no Manimani',
  u'sora no otoshimono': u'Sora no Otoshimono',
  u'sora no woto': u'Sora no Woto',
  u'soul eater': u'Soul Eater',
  u'space brothers': u'Space Brothers',
  u'spice & wolf': u'Spice and Wolf',
  u'spice and wolf': u'Spice and Wolf',
  u'spice and wolf ': u'Spice and Wolf',
  u'spiral': u'Spiral: Suiri no Kizuna',
  u'spirited away': u'Spirited Away',
  u'star driver': u'Star Driver',
  u'star driver or fmab': u'Star Driver',
  u'stein\'s gate': u'Steins;Gate',
  u'stein\'s;gate': u'Steins;Gate',
  u'stein;s gate': u'Steins;Gate',
  u'steins : gate': u'Steins;Gate',
  u'steins gate': u'Steins;Gate',
  u'steins:gate': u'Steins;Gate',
  u'steins:gate / bakemonogatari / spice and wolf': u'Spice and Wolf',
  u'steins; gate': u'Steins;Gate',
  u'steins;fate': u'Steins;Gate',
  u'steins;gate': u'Steins;Gate',
  u'steinsgate': u'Steins;Gate',
  u'stellvia': u'Stellvia',
  u'strike witches': u'Strike Witches',
  u'summer wars': u'Summer Wars',
  u'super dimension fortress macross': u'Macross Series',
  u'suzumiya haruhi': u'Haruhi Suzumiya Series',
  u'suzumiya haruhi no shoushitsu': u'Haruhi Suzumiya Series',
  u'suzumiya haruhi no yuutsu': u'Haruhi Suzumiya Series',
  u'sword art online': u'Sword Art Online',
  u'tatami galaxy': u'The Tatami Galaxy',
  u'techni muyo series': u'Tenchi Muyo Ryo Ohki',
  u'tenchi muyo': u'Tenchi Muyo Ryo Ohki',
  u'tenchi muyo!': u'Tenchi Muyo Ryo Ohki',
  u'tenga toppa gurren lagann': u'Tengen Toppa Gurren Lagann',
  u'tengen toppa gurren lagann': u'Tengen Toppa Gurren Lagann',
  u'tengen toppa gurren lagann ': u'Tengen Toppa Gurren Lagann',
  u'tengen toppa gurren laggan': u'Tengen Toppa Gurren Lagann',
  u'that\'s a tie! i can\'t pick between azumanga daioh and panty and stocking': u'Panty & Stocking with Garterbelt',
  u'the disappearance of haruhi suzumiya': u'',
  u'the dissaperance of haruhi suzumiya': u'',
  u'the ef series': u'ef: tale of series',
  u'the girl who leapt through time': u'The Girl Who Leapt Through Time',
  u'the melancholy of haruhi suyzumiya': u'Haruhi Suzumiya Series',
  u'the melancholy of haruhi suzumiya': u'Haruhi Suzumiya Series',
  u'the melancholy of haruhi uzu': u'Haruhi Suzumiya Series',
  u'the melancholy of suzumiya haruhi': u'Haruhi Suzumiya Series',
  u'the new prince of tennis': u'New Prince of Tennis',
  u'the tatami galaxy': u'The Tatami Galaxy',
  u'the tatami galexy': u'The Tatami Galaxy',
  u'tiger & bunny': u'Tiger & Bunny',
  u'tiger and bunny': u'Tiger & Bunny',
  u'to aru kagaku no railgun': u'Toaru Kagaku no Railgun',
  u'to aru majutsu no index': u'Toaru Majutsu no Index',
  u'toaru majutsu no index': u'Toaru Majutsu no Index',
  u'toki wo kakeru shojou': u'The Girl Who Leapt Through Time',
  u'toki wo kakeru shoujo': u'The Girl Who Leapt Through Time',
  u'tokyo godfathers': u'Tokyo Godfathers',
  u'tokyo magnitude 8.0': u'Tokyo Magnitude 8.0',
  u'toradora': u'Toradora!',
  u'toradora!': u'Toradora!',
  u'toradora!!': u'Toradora!',
  u'touch': u'Touch',
  u'tough call, but if i have to pick one, it would probably be dantalian no shoka': u'Dantalian no Shoka',
  u'trigun': u'Trigun',
  u'trigun ': u'Trigun',
  u'trigun, at the momment': u'Trigun',
  u'ttgl': u'Tengen Toppa Gurren Lagann',
  u'twelve kingdoms': u'Juuni Kokuki',
  u'un-go': u'Un-Go',
  u'usagi drop': u'Usagi Drop',
  u'vampire hunter d: bloodlust': u'Vampire Hunter D: Bloodlust',
  u'video girl ai': u'Video Girl Ai',
  u'vision of escaflowne': u'The Vision of Escaflowne',
  u'voices of a distant star': u'Voices of a Distant Star',
  u'welcome to the n.h.k.': u'Welcome to the N.H.K.',
  u'welcome to the nhk': u'Welcome to the N.H.K.',
  u'welcome to the nhk!': u'Welcome to the N.H.K.',
  u'wings of honneamise': u'The Wings of Honneamise',
  u'wolf\'s rain': u'Wolf\'s Rain',
  u'working!!': u'Working!!',
  u'xxxholic': u'xxxHolic',
  u'yosuga no sora': u'Yosuga no Sora',
  u'yu-gi-oh 5d\'s': u'Yu-Gi-Oh! 5D\'S',
  u'yu-yu hakasho': u'YuYu Hakusho',
  u'yuruyuri': u'Yuru Yuri',
  u'yuyu hakusho': u'YuYu Hakusho',
  u'zatch bell': u'Zatch Bell!',
  u'zero no tsukaima': u'Zero no Tsukaima',
  u'zeta gundam': u'Gundam Series',
  u'魔法少女まどか☆マギカ': u'Puella Magi Madoka Magica',
  u'魔法少女マドカ☆マギカ': u'Puella Magi Madoka Magica',
  u'ａｎｇｅｌ　ｂｅａｔｓ！': u'Angel Beats!',
}
